CREATE DATABASE LOGIN;
USE LOGIN;
CREATE TABLE USUARIO(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    USERNAME VARCHAR(512) NOT NULL UNIQUE,
    PASSWORD VARCHAR(512) NOT NULL
);

-- inserir um usuário de exemplo, admin
INSERT INTO USUARIO(USERNAME,PASSWORD) VALUES ('admin','admin')